[package]
name = "message-template"
version = "0.1.0"
edition = "2021"

description = "A simple templating language for generating short messages, with support for all the necessary statements and expressions."
license = "MIT"
repository = "https://github.com/banocean/message-template.git"
homepage = "https://github.com/banocean/message-template"

[features]
serde = ["serde_json", "dep:serde"]

[dependencies]
serde_json = { optional = true, version = "1.0" }
serde = { optional = true, version = "1.0", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }